language: node_js
node_js:
- '8'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
before_install:
- set -e
install:
- export CXX="g++-5"
- npm install
script:
- npm test

notifications:
  on:
    tags: true
  slack:
    secure: Cc1Sol29B89N7aJXHS4tDtSwcsUj0Tz6y2+lWBbUY1ueTugfa0J1bfC2p180RVahxBVm6qLuSf7bDwF1TgCycEO69vqB+L837Bf2CPIuLKa3QUOL5+etJtY5sZVrcmfaxwQoDBCZ3yhq7vCpCKGz5up/qKtBO37REVTkL+QQiu+S+jm0WXdYQSnZQiBBGVWL38PzVv9kkfC6ZrQDoDdbIaeXgb3XqBBa4Vuf2Iyw983qmuijwwIivulhw2tBYsy90BMjmSZZ3T1HSK4g1D0lbGCZgYrjIFMvbdTYilkbCJmnA3NlNCLHMnMESz+oSYBhL3u3h0Phht9iDg1yFvYZLj2Wu3ajU0ODAzZQLlhGBsTPLBFdT+RoxdnkZ8v0Mc/MCquXlz2MGQT7K8qY9UTN6xx0399aKpVXbwsIXgTHAw3V7JdtaPFQTHQnKBHyjJ0zhvKotuXXFJlCbj0+S/qaXJCb42ua7FJwt+O4MkMIBovdHFM+ZMATAnvI/AlXkGQArCqtJWUo0XYEB5e/IMlSnjXBvxR/1sN77KkV2xX2HxubYa7yXW79nh9bZ4h0E1lKD3CwgXZfeoQVxxl6cKYbUX15nfa82TA9PdZ9Fq9BBDQbpSDKuu2UbVXi7v8kuSb+aB0dJJzrqq8lzAcgb2kPhkIGSHO6fiiUh9l9QjGMvwg=
