version: 2
jobs:
  test-node-10:
    docker:
      - image: circleci/node:10
    working_directory: ~/fly
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v2-dependencies-{{ .Branch }}
      - run: yarn install
      - run: yarn bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn build
      - run: yarn bundle
      - run: yarn test
